package com.ch.money.mapper;

import com.ch.money.model.FinanceAccount;
import org.springframework.stereotype.Repository;

import java.util.Map;

@Repository
public interface FinanceAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    int insert(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    int insertSelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    FinanceAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    int updateByPrimaryKeySelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    int updateByPrimaryKey(FinanceAccount record);
    //登录后：根据用户编号查询用余额
    FinanceAccount selectFinanceByUserId(Integer userId);
    //投资：余额减少
    int updateMoneyReduceForInvest(Map<String, Object> parasMap);
}