package com.ch.money.mapper;

import com.ch.money.model.LoanInfo;
import com.ch.money.model.PageModel;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface LoanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    LoanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    int updateByPrimaryKeySelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Thu Jul 07 19:42:13 CST 2022
     */
    int updateByPrimaryKey(LoanInfo record);

    //查询历史年华收益率
    Double selectLoanInfoHistoryRateAvg();

    //首页：根据产品类型和数量  查询产品信息
    List<LoanInfo> selectLoanInfosByTypeAndNum(Map<String, Object> parasMap);

    //根据产品类型与分页模型查询产品信息
    List<LoanInfo> selectLoanInfosByTypeAndPageModel(Map parasMap);
    //查询总记录数
    Long selectLoanInfoCountByType(Integer ptype);
    //投资：减少剩余金额
    int updateLeftMoneyReduceForInvest(Map<String, Object> parasMap);
}